[package]
name = "bloom_filter"
version = "0.1.0"
authors = ["Tulio Barbosa <tulio.gomesbarbosa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
